
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.ConnectionProvider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author JAY
 */
public class billing extends javax.swing.JFrame {

    public int finalTotal = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(billing.class.getName());

    /**
     * Creates new form billing
     */
    public billing() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel5.setText(dFormat.format(date));
       

        LocalDate today = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE", Locale.ENGLISH);
        String dayOfWeek = today.format(formatter);
        jLabel6.setText(dayOfWeek);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(90, 120));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing frame.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Day:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1158, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Buyer Detail :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 136, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 177, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contact No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 177, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 176, 200, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 177, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 176, 200, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 535, 50, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Product Detail :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Product Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Measure");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Rate");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 38, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Quantity");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.addActionListener(this::jTextField5ActionPerformed);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 100, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
        });
        jTextField7.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTextField7CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField7InputMethodTextChanged(evt);
            }
        });
        jTextField7.addActionListener(this::jTextField7ActionPerformed);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Calculation Details:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 1158, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 1158, 10));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Measure", " Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 501, 198));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Total  Payee");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 200, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing ani.gif"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing background.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new billing().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        String pname = jTextField4.getText(); 
        String measure = jTextField5.getText();
  
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from product Where pname='" + pname + "' AND  pMeasure = '" + measure + "'");
            if (rs.next()) {
                jTextField4.setText(rs.getString(2));
                jTextField5.setText(rs.getString(3));
                jTextField6.setText(rs.getString(5));
                jTextField7.setText("1");

            } else {
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");

            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(jTextField6.getText());
        int Qty = Integer.parseInt(jTextField7.getText());
        
        
        int total = price * Qty;
//        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
//        tableModel.addRow(new Object[]{jTextField4.getText(), jTextField5.getText(), price, jTextField7.getText(), total});
       

        String qty=jTextField7.getText();
        String pname=jTextField4.getText();
        String measure=jTextField5.getText();
        
        

        try {
            int pQty = Integer.parseInt(jTextField7.getText());
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Qty from product where pname ='"+pname+"'AND pMeasure='"+measure+"' "); // Add appropriate WHERE clause
    
            if (rs.next()) {
                int dbQty = rs.getInt("Qty");
        
                if (pQty > dbQty) {  // Changed condition: if requested quantity > available quantity
                    JOptionPane.showMessageDialog(null, "Insufficient Stock ,Available Qty is:"+dbQty);
                } else {
                        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                        tableModel.addRow(new Object[]{jTextField4.getText(), jTextField5.getText(), price, jTextField7.getText(), total});
                        try{st.executeUpdate("update product set Qty=Qty-'"+qty+"' WHERE pname ='"+pname+"' AND pMeasure ='"+measure+"'"); } 
                        catch(Exception e){}
                        finalTotal = finalTotal + total;
                        String totall = String.valueOf(finalTotal);
                        jTextField8.setText(totall);
                        
                }
                 }
    
   
    
}  catch (Exception e) {} 
 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        String pname=jTextField4.getText();
        String measure = jTextField5.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from product Where pMeasure='" + measure + "' AND pname='" + pname + "'");
            if (rs.next()) {
                jTextField4.setText(rs.getString(2));
                jTextField5.setText(rs.getString(3));
                jTextField6.setText(rs.getString(5));
                jTextField7.setText("1");

            } else {
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 String name = jTextField1.getText();
String contactNo = jTextField2.getText();
String address = jTextField3.getText();
String path = "C:\\Invoices\\";


// Create directory if it doesn't exist
File directory = new File(path);
if (!directory.exists()) {
    directory.mkdirs();
}

String fileName = path + name + "_" + jLabel5.getText().replace("/", "-") + ".pdf";
com.itextpdf.text.Document doc = new com.itextpdf.text.Document(PageSize.A4);

try {
    PdfWriter.getInstance(doc, new FileOutputStream(fileName));
    doc.open();
    
    // Add logo or header with better formatting
    Font headerFont = new Font(Font.FontFamily.HELVETICA, 34, Font.BOLD);
    Font normalFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
    Font Fonts = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD);
    Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
    
    // Company Header
    Paragraph companyName = new Paragraph("ARIHANT LUBRICANT", headerFont);
    companyName.setAlignment(Element.ALIGN_CENTER);
    doc.add(companyName);
    doc.add(new Paragraph(" "));
    Paragraph contact = new Paragraph();
    contact.add(new Chunk("Contact No:",Fonts ));
    contact.add(new Chunk(" 8208405026", normalFont));
    contact.setAlignment(Element.ALIGN_RIGHT);
    doc.add(contact);
    
    Paragraph line = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------");
    line.setAlignment(Element.ALIGN_CENTER);                                                                                                                             
    doc.add(line);                                                                                                                                                       
                                                                                                                                    
    // Date and Buyer Details
    Paragraph dateTime = new Paragraph("Date: " + jLabel5.getText()+"");
    dateTime.setAlignment(Element.ALIGN_RIGHT); 
    Paragraph date = new Paragraph("Day: " + jLabel6.getText()+"      ");
    date.setAlignment(Element.ALIGN_RIGHT);
    doc.add(dateTime);
    doc.add(date);
    
    doc.add(new Paragraph(" ")); // Empty line
    
    Paragraph buyerTitle = new Paragraph("Buyer Details:", boldFont);
    doc.add(buyerTitle);
    
    doc.add(new Paragraph("Name: " + name, normalFont));
    doc.add(new Paragraph("Contact No: " + contactNo, normalFont));
    doc.add(new Paragraph("Address: " + address, normalFont));
    
    doc.add(new Paragraph(" ")); // Empty line
    
    // Create table with better formatting
    PdfPTable table = new PdfPTable(5);
    table.setWidthPercentage(100);
    table.setSpacingBefore(10f);
    table.setSpacingAfter(10f);
    
    // Set column widths
    float[] columnWidths = {3f, 2f, 2f, 2f, 2f};
    table.setWidths(columnWidths);
    
    // Table headers with background
    PdfPCell cell = new PdfPCell(new Phrase("Item Name", boldFont));
    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(cell);
    
    cell = new PdfPCell(new Phrase("Measures", boldFont));
    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(cell);
    
    cell = new PdfPCell(new Phrase("Rate ", boldFont));
    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(cell);
    
    cell = new PdfPCell(new Phrase("Quantity", boldFont));
    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(cell);
    
    cell = new PdfPCell(new Phrase("Total", boldFont));
    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
    table.addCell(cell);
    
   
    
    // Add table data
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        String itemName = jTable1.getValueAt(i, 0).toString();
        String measure = jTable1.getValueAt(i, 1).toString();
        String rate = jTable1.getValueAt(i, 2).toString();
        String quantity = jTable1.getValueAt(i, 3).toString();
        String total = jTable1.getValueAt(i, 4).toString();
        
        
        // Calculate grand total
       
        
        table.addCell(new PdfPCell(new Phrase(itemName, normalFont)));
        table.addCell(new PdfPCell(new Phrase(measure, normalFont)));
        table.addCell(new PdfPCell(new Phrase(rate, normalFont)));
        table.addCell(new PdfPCell(new Phrase(quantity, normalFont)));
        
        PdfPCell totalCell = new PdfPCell(new Phrase(total, normalFont));
        totalCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        table.addCell(totalCell);
    }
    
    doc.add(table);
    
   
    Paragraph totalParagraph = new Paragraph();
    totalParagraph.setAlignment(Element.ALIGN_RIGHT);
    
    Chunk totalText = new Chunk("Grand Total:", boldFont);
    Chunk totalValue = new Chunk(jTextField8.getText() + "/-", new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));
    
    totalParagraph.add(totalText);
    totalParagraph.add(totalValue);
    doc.add(totalParagraph);
    
    // Add footer
    doc.add(new Paragraph(" ")); // Empty line
    doc.add(new Paragraph(" ")); // Empty line
    
    Paragraph footer = new Paragraph("Thank you for your business!", normalFont);
    footer.setAlignment(Element.ALIGN_CENTER);
    doc.add(footer);
    
    Paragraph terms = new Paragraph("* This is a computer generated invoice", new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC));
    terms.setAlignment(Element.ALIGN_CENTER);
    doc.add(terms);
    
    doc.close();
    
    JOptionPane.showMessageDialog(null, "Bill Generated Successfully!\nSaved at: " + fileName);
    
    // Open the PDF automatically
    try {
        Desktop.getDesktop().open(new File(fileName));
    } catch (Exception e) {
        // Handle if can't open automatically
    }
    
    setVisible(false);
    new billing().setVisible(true);
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error generating bill: " + e.getMessage());
    e.printStackTrace();
}      
//        SimpleDateFormat dForm = new SimpleDateFormat("dd-MM-yyyy");
//        String date = jLabel5.getText();
       
        for (int i = 0; i < jTable1.getRowCount(); i++) {
        String product_name = jTable1.getValueAt(i,0).toString();
        String product_measure = jTable1.getValueAt(i,1).toString();
        String unit_price = jTable1.getValueAt(i,2).toString();
        String quantity = jTable1.getValueAt(i,3).toString();
        String line_total = jTable1.getValueAt(i,4).toString();
        String buyer_name = jTextField1.getText();
        String buyer_phone=jTextField2.getText();
        String buyer_address=jTextField3.getText();
        String grand_total= jTextField8.getText();
        String bill_Time= jLabel5.getText();
        
        

       


        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into bills_details Values('"+buyer_name+"','"+buyer_phone+"','"+buyer_address+"','"+product_name+"','"+product_measure+"','"+unit_price+"','"+quantity+"','"+line_total+"','"+grand_total+"','"+bill_Time+"')");
           
        }
        catch(Exception e){
             
        }
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed

    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField7FocusGained

    private void jTextField7CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField7CaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField7CaretPositionChanged

    private void jTextField7InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField7InputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField7InputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new billing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
